### ISSUE TITLE
Support installing multiple ruby versions

### ISSUE THREAD

**Issue by pcriv** [josemrb/vboxes#4] opened 2014-10-31 15:00 UTC
If possible support installing multiple ruby versions specified in the `.vagrantuser` file

**Comment by josemrb** [comment] 2015-01-30 20:46
At this moment that feature doesn't fit the scope of the project
Won't fix
By design

**Closed as completed by josemrb** 2015-01-30 20:46 UTC

**Comment by pablocrivella** [comment] 2015-01-30 20:48
If you are interested in adding support for this later.. https://github.com/pablocrivella/ansible-role-rbenv
